### ISSUE TITLE
Connecting with the Astrobee Simulator

### ISSUE THREAD

**Issue by erobinson-1997** [nasa/astrobee_gds#2]
I am using a binary version of the GDS Control Station software, and I am having trouble connecting with the `astrobee` simulator. In the screenshot below I have the both the simulator and the GDS software running on the same computer. The Master_URI was also added to NDDS_DISCOVERY_PEERS. The buttons and options are greyed out, do they automatically enable when the GDS software receives something from the guest science manager?

![image](https://github.com/nasa/astrobee_gds/assets/131702292/3b9e947a-9703-4e31-a5c6-f20eb9f1151d)

**Comment by bcoltin** [comment]
Sorry, I realized we haven't been checking the Astrobee GDS repo and missed both your issues. If you have any future issues please post them on the main Astrobee repo and we will be more likely to see them. Our apologies!
